Add property to get local endpoint of discovered NAT device
lontivero/Open.NAT pull request #101
Opened 2021-01-17 15:37 UTC by CdecPGL

I added properties to get the local endpoint of NAT device and the IP address of the client which connected to the NAT device.
This is related to #37 .

I have added two properties as below to `NatDevice` class and implemented overrides to child classes.

- HostEndPoint: the local endpoint of NAT device
- LocalAddress:  the IP address of the client which connected to the NAT device

## `UpnpNatDevice` class

I used `UpnpNatDeviceInfo`.

- HostEndPoint: UpnpNatDeviceInfo.HostEndPoint
- LocalAddress: UpnpNatDeviceInfo.LocalAddress

## `PmpNatDevice` class

The meaning of `LocalAddress` in `PmpNatDevice` class was same as the meaning of `HostEndPoint.Address` in `UpnpNatDeviceInfo` class, so I changed `LocalAddress` to `HostEndPoint` and add new `LocalAddress`.

I set the port of `HostEndPoint` as `PmpConstants.ServerPort` because old `LocalAddress` was used that way in other parts of codes.

2021-01-17 19:56 UTC, lontivero commented
This PR will not compile for c# 3.0 because the expression bodied members were introduced much much recently. I think it could be a good idea to migrate the projects to dotnet 3.1 and then introduce changes like these ones.

2021-01-18 14:51 UTC, CdecPGL commented
Thank you for checking my PR.
I have changed codes to be compilable for C# 3.0.

2021-01-20 14:25 UTC, lontivero requested changes
Can you fix the identation? It seems you are mixing tabs and spaces.

2021-01-20 15:10 UTC, CdecPGL commented
I'm sorry. I forget to unify indentation.
I fixed indentation to tabs.

2021-01-20 17:02 UTC, merged